name: memoryfun
description: My entry for ludum dare 53.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.11+11

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  riverbloc: ^2.1.0
  freezed_annotation: ^2.2.0
  auto_route: ^6.4.0
  flutter_riverpod: ^2.3.6
  audioplayers: ^5.2.1
  flutter_animate: ^4.1.1+1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  freezed: ^2.3.2
  lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/color/
    - assets/color/food/
    - assets/color/mail/
    - assets/color/babies/
    - assets/color/babiesComplex/
    - assets/color/other/
    - assets/color/jungle/
    - assets/color/club/
    - assets/color/farm/
    - assets/color/farmComplex/
    - assets/color/farmMud/
    - assets/color/numbers/
    - assets/color/texts/
    - assets/color/differentNumbers/
    - assets/color/onlyColors/
    - assets/color/christmas/
    - assets/color/emotions/
    - assets/color/emotionsText/
    - assets/color/farmAnimalsText/
    - assets/color/farmAnimals/
    - assets/color/gameTypeThumbnails/
    - assets/mono/
    - assets/mono/food/
    - assets/mono/mail/
    - assets/mono/babies/
    - assets/mono/babiesComplex/
    - assets/mono/other/
    - assets/mono/jungle/
    - assets/mono/club/
    - assets/mono/farm/
    - assets/mono/farmComplex/
    - assets/mono/farmMud/
    - assets/mono/numbers/
    - assets/mono/texts/
    - assets/mono/differentNumbers/
    - assets/mono/onlyColors/
    - assets/mono/christmas/
    - assets/mono/emotions/
    - assets/mono/emotionsText/
    - assets/mono/farmAnimalsText/
    - assets/mono/farmAnimals/
    - assets/mono/gameTypeThumbnails/